### ISSUE TITLE
Support Level 5 speed in firmware versions past 1.7.6

### ISSUE THREAD

**Issue by wmmiii** [mjarkk/vanmoof-web-controller#56]
It looks as if the application is unable to set speed level 5 with firmware versions past 1.7.6.

https://github.com/mjarkk/vanmoof-web-controller/blob/97a3f959df1fdaa98836ce1dfac0513961e60369/components/Controls.tsx#L272-L275

Did Vanmoof remove support for this speed level? Is it possible with newer firmware versions to set this speed?

**Comment by attilatdeak** [comment]
Since vanmoof removed assist 5 and offroad/test mode from the options list in the firmwares from 1.8.1 and above, of course you cant set it. Someone have figured out how to hack it back because the function is still there in the firmware, but as far as i understand they need physical access to the cartridge to do so.

**Comment by wmmiii** [comment]
Yeah, that was my fear, I thought I'd add something to the issue tracker to make it explicit.

Thanks!
